export const defaultStatisticData = [
  { metricName: "total assets", value: null, percentile: "" },
  { metricName: "deposit", value: null, percentile: "" },
  { metricName: "collateral", value: null, percentile: "" },
  { metricName: "debt", value: null, percentile: "" },
];

export const metricConfigs = [
  {
    name: "asset",
    label: "Total Assets",
    color: "purple-bar",
  },
  {
    name: "collateral",
    label: "Collateral",
    color: "orange",
  },
  {
    name: "deposit",
    label: "Deposit",
    color: "blue-chart",
  },
  {
    name: "debt",
    label: "Debt",
    color: "pink",
  },
];

export const iconColorMapping = {
  AAVE: "#B6509E",
  AMPL: "#ffffff",
  BAL: "#1E1E1E",
  BAT: "#FF5000",
  BUSD: "#F0B90B",
  CRV: "#00A8FF",
  DAI: "#FBAF1B",
  DPI: "#8150E6",
  ENJ: "#7866D5",
  ENS: "#5298FF",
  ETH: "#627EEA",
  FEI: "#22996E",
  FIL: "#0090FF",
  FRAX: "#000000",
  GUSD: "#00DCFA",
  KNC: "#31CB9E",
  LINK: "#2A5ADA",
  LUNA: "#FFD83D",
  MANA: "#FF2D55",
  MKR: "#4FA89B",
  RAI: "#18c9aa",
  REN: "#001C3A",
  SNX: "#09d1ff",
  STETH: "#00a3ff",
  SUSD: "#000000",
  TUSD: "#002868",
  UNI: "#fe007a",
  USDC: "#236AC3",
  USDP: "#BAD147",
  USDT: "#50AF95",
  WBTC: "#F09242",
  WETH: "#EC1C79",
  XSUSHI: "#FF9A61",
  YFI: "#0077FC",
  ZRX: "#000000",
};
