import { ReportAssetResult } from "@/types/api";

export const defaultStatisticData = [
  { metricName: "net assets", value: null, percentile: "" },
  { metricName: "deposit", value: null, percentile: "" },
  { metricName: "collateral", value: null, percentile: "" },
  { metricName: "debt", value: null, percentile: "" },
];

export const assetsData: Partial<ReportAssetResult> = {
  symbols: [
    {
      symbol: "eth",
      protocol: "etherum",
      chain: "etherum",
      debt: "41987",
      collateral: "5678",
      asset: "6322",
      deposit: "12000",
    },
    {
      symbol: "usdc",
      protocol: "etherum",
      chain: "etherum",
      debt: "21987",
      collateral: "2345",
      asset: "-1245",
      deposit: "1100",
    },
    {
      symbol: "uni",
      protocol: "etherum",
      chain: "etherum",
      debt: "11987",
      collateral: "1234",
      asset: "8535",
      deposit: "9769",
    },
    {
      symbol: "dai",
      protocol: "etherum",
      chain: "etherum",
      debt: "8987",
      collateral: "3456",
      asset: "2313",
      deposit: "5769",
    },
  ],
};
export const metricConfigs = [
  {
    name: "asset",
    label: "Net Assets",
    color: "purple-bar",
  },
  {
    name: "deposit",
    label: "Deposit",
    color: "blue-chart",
  },
  {
    name: "collateral",
    label: "Collateral",
    color: "orange",
  },
  {
    name: "debt",
    label: "Debt",
    color: "red",
  },
];
export const iconColorMapping = {
  AAVE: "#B6509E",
  AMPL: "#ffffff",
  BAL: "#1E1E1E",
  BAT: "#FF5000",
  BUSD: "#F0B90B",
  CRV: "#00A8FF",
  DAI: "#FBAF1B",
  DPI: "#8150E6",
  ENJ: "#7866D5",
  ENS: "#5298FF",
  ETH: "#627EEA",
  FEI: "#22996E",
  FIL: "#0090FF",
  FRAX: "#000000",
  GUSD: "#00DCFA",
  KNC: "#31CB9E",
  LINK: "#2A5ADA",
  LUNA: "#FFD83D",
  MANA: "#FF2D55",
  MKR: "#4FA89B",
  RAI: "#18c9aa",
  REN: "#001C3A",
  SNX: "#09d1ff",
  STETH: "#00a3ff",
  SUSD: "#000000",
  TUSD: "#002868",
  UNI: "#fe007a",
  USDC: "#236AC3",
  USDP: "#BAD147",
  USDT: "#50AF95",
  WBTC: "#F09242",
  WETH: "#EC1C79",
  XSUSHI: "#FF9A61",
  YFI: "#0077FC",
  ZRX: "#000000",
};
